services:
  members-ms-db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: members
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

volumes:
  postgres:
